version: '3.9'

services:
  api:
    container_name: api_container
    image: api_image
    build:
      context: api
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db_container
    image: postgres:alpine3.17
    ports:
      - "5432:5432"
    env_file:
    - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    profiles:
      - "dev"
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"


volumes:
  postgres_data:
  pgadmin_data:

